AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  UseCache: false
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "pkg/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Exclude:
    - "bin/coverage"

Style/OneClassPerFile:
  Exclude:
    - "bin/coverage"

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "spec/**/*.rb"

Metrics/MethodLength:
  Max: 32

Metrics/AbcSize:
  Max: 45

Metrics/ClassLength:
  Max: 130
  CountAsOne:
    - hash

Metrics/ModuleLength:
  Max: 130

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/ParameterLists:
  Max: 8
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 12

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/HashAlignment:
  Enabled: false
